# Generated by Django 6.0.3 on 2026-03-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='venue',
            name='sport_categories_rel',
            field=models.ManyToManyField(blank=True, related_name='venues', to='api.sportcategory'),
        ),
    ]
